server:
 port: 8762 #8763

spring:
  application:
    name: service-hi
  zipkin:
    enabled: true
    base-url: http://localhost:9411


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

